### ISSUE TITLE
Upgrading node with the same tag latest causing issues

### ISSUE THREAD

**Issue by remyoucef** [apify/apify-actor-docker#17]
Upgrading node (eg. from 10 to 12) is causing some issues including but not limited to:
- Node TLS version incompatibility which is solved by adding argument "--tls-min-v1.0" to npm start script.
- Inconsistency in screenshots taken by puppeteer (same chrome and puppeteer versions) which requires old builds with node 10.
- #16 

Some of the issues can be solved with ease but others require a few changes in this project.

**Comment by remyoucef** [comment]
Can you please take a look at this?

**Comment by jancurn** [comment]
@remyoucef please can you suggest how we could easily fix this, without a need to downgrade to Node 10? E.g. `--tls-min-v1.0` can be added easily, but I don't know about the screenshots...

**Comment by remyoucef** [comment]
I think about specifying the base node image by passing an argument during the build and publish of images
https://www.jeffgeerling.com/blog/2017/use-arg-dockerfile-dynamic-image-specification
What do you think?

**Comment by jancurn** [comment]
Yeah, good idea, I guess we could use this internally to generate base images with both Node 10 and 12. Is that what you meant?

**Comment by remyoucef** [comment]
Yes.

**Comment by jancurn** [comment]
Cool. Unfortunately, I don't really know when we'll be able to get to this...

**Comment by remyoucef** [comment]
No problem. Just take it into consideration...

**Comment by B4nan** [comment]
I believe this has been already addressed, given we publish docker images tagged based on node versions, so closing.
