### ISSUE TITLE
Fix error when starting XVFB in the node-chrome-xvfb image

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-actor-docker#22]
Because of a permissions mismatch, XVFB can't create the default UNIX socket in `/tmp`, and logs an error `_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created`.

If we don't need the UNIX socket, perhaps it can be solved by adding `-nolisten unix` to the `xvfb` arguments, similar to here:
https://phabricator.wikimedia.org/T202710

**Comment by metalwarrior665** [comment]
Apparently, it should be fixed by 

```
it can be solved by adding this at the end of the dockerfile 
USER root RUN mkdir -p /tmp/.X11-unix
```

**Comment by jancurn** [comment]
Attempted fix here: https://github.com/apify/apify-actor-docker/pull/23

**Comment by mnmkng** [comment]
@jancurn  It did something, but now there's this:
![image](https://user-images.githubusercontent.com/23726914/103292037-565dd980-49ed-11eb-8501-1047d4843cf7.png)

**Comment by jancurn** [comment]
Hm, at least some progress, we can try adding the chmod, maybe it will
magically just work

**Comment by B4nan** [comment]
I guess this is no longer valid? Never seen this in the logs.

**Comment by metalwarrior665** [comment]
I think this is probably only with the old Dockerfiles
