### ISSUE TITLE
Error launching apify/actor-node-chrome-xvfb:latest

### ISSUE THREAD

**Issue by RicardoVaranda** [apify/apify-actor-docker#28]
When trying to launch it via command line:

```
docker run -e PUPPETEER_EXECUTABLE_PATH="/usr/bin/google-chrome-stable" --rm -v $(pwd):/app -w app -it apify/actor-node-chrome-xvfb:latest
```

I am receiving the following error:

```
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r818858 is guaranteed to work.
```

**Comment by mnmkng** [comment]
Is this a first time you're using the image or has it been working for you like this until now?

**Comment by RicardoVaranda** [comment]
Hi @mnmkng , yes this is the first time I'm trying to run it.

**Comment by mnmkng** [comment]
```bash
docker run -it apify/actor-node-chrome-xvfb
```
Works fine for me. It must be something with your configuration. For example you're launching `google-chrome-stable` but we're normally launching `google-chrome` in the base Dockerfile.

```
ENV APIFY_CHROME_EXECUTABLE_PATH=/usr/bin/google-chrome
```

**Comment by RicardoVaranda** [comment]
It seems like the issue is when I try to attach a chrome extension to puppeteer using:

```
  args: [
    '--disable-extensions-except=/path/to/extension/',
    '--load-extension=/path/to/extension/',
  ]
```

As mentioned here:
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#working-with-chrome-extensions

**Comment by mnmkng** [comment]
Are you running it directly with `puppeteer` as in the example, or with `apify`? If you're using Puppeteer directly, you need to turn off sandboxing or provide your own sandbox.

```js
args: ['--no-sandbox']
```

Otherwise, no idea, maybe the paths to the extension are not correct? Or the extension itself is buggy? Does not seem like an issue with the image itself.

**Comment by RicardoVaranda** [comment]
We are already passing in:

args: ['--no-sandbox']

Along with:

args: [
'--no-sandbox',
'--disable-setupid-sandbox',
'--disable-dev-shm-usage',
]

As well as the ones mentioned above for the extension.

**Comment by mnmkng** [comment]
Can you try the `apify/actor-node-puppeteer-chrome` image please? It's a new one we published recently.
