### ISSUE TITLE
Image with Node v14 and Puppeteer v11 not found

### ISSUE THREAD

**Issue by rubydev** [apify/apify-actor-docker#71]
Hi, based on documentation [here](https://sdk.apify.com/docs/guides/docker-images#automation-library-versioning) I would like to use Docker image with Node v14, and Puppeteer v11. But it looks, that it doesn't exist:

```
2021-11-29T09:17:40.233Z ACTOR: Cloning git@github.com:apify-projects/Apify-TopMonks-PG#master:stopandshop
2021-11-29T09:17:41.090Z ACTOR: Cloned commit ID: d196358f229479cdc1a58b2a5d922b88ab62e286
2021-11-29T09:17:41.121Z ACTOR: Cloned branch name: master
2021-11-29T09:17:41.153Z ACTOR: Extracting actor documentation from README.md
2021-11-29T09:17:41.327Z ACTOR: Extracting input schema from INPUT_SCHEMA.json
2021-11-29T09:17:41.361Z ACTOR: Building Docker image.
2021-11-29T09:17:41.491Z Step 1/18 : FROM apify/actor-node-puppeteer-chrome:14-11.0.0
2021-11-29T09:17:41.572Z ACTOR: ERROR: Docker image build failed: manifest for apify/actor-node-puppeteer-chrome:14-11.0.0 not found: manifest unknown: manifest unknown
```

If I will try `apify/actor-node-puppeteer-chrome:14` it is installing Puppeteer version 12, and there is some bug [here](https://github.com/puppeteer/puppeteer/issues/7805). So I would like to avoid using Puppeteer version 12 for now. In docker hub I found only `14-11.0.0-beta`

**Comment by B4nan** [comment]
Puppeteer v11 is not yet supported, will be in next SDK version, which will then automatically trigger build of such image.

Should be out later this week, rather sooner than later.

**Comment by B4nan** [comment]
Btw node 14 you say? So you are not using SDK v2 (it requires node 15+)?

> If I will try apify/actor-node-puppeteer-chrome:14 it is installing Puppeteer version 12, and there is some bug here. So I would like to avoid using Puppeteer version 12 for now. 

@vladfrangu please make sure this works as expected. if the latest stable image tries to install puppeteer 12 than this should get priority, as it is unsupported for us (the PR in SDK even has errors, so its not just about chrome 97)

**Comment by rubydev** [comment]
> Btw node 14 you say? So you are not using SDK v2 (it requires node 15+)?
> 

Yes, I meant 14 (for this project we using SDK v1).

**Comment by vladfrangu** [comment]
> > If I will try apify/actor-node-puppeteer-chrome:14 it is installing Puppeteer version 12, and there is some bug here. So I would like to avoid using Puppeteer version 12 for now.
> 
> @vladfrangu please make sure this works as expected. if the latest stable image tries to install puppeteer 12 than this should get priority, as it is unsupported for us (the PR in SDK even has errors, so its not just about chrome 97)

I just pulled the image locally (`docker pull apify/actor-node-puppeteer-chrome:14`) and ran it (`docker run --rm -it  apify/actor-node-puppeteer-chrome:14`), and it installed puppeteer 10.4.0. I seriously don't know how it installed puppeteer 12 for you.. Did you override the package.json/have a package-lock present in your usage of the image that sets puppeteer to a different version?

**Comment by B4nan** [comment]
Is this still valid @rubydev?

**Comment by rubydev** [comment]
@B4nan No, we can close it. Thanks
