### ISSUE TITLE
Build is not using correct version of Puppeteer

### ISSUE THREAD

**Issue by rubydev** [apify/apify-actor-docker#72]
According to documentation [here](https://sdk.apify.com/docs/guides/docker-images#best-practices) is recommended not set specific version of Puppeteer to package.lock. Should be used version of Puppeteer which is pre-installed in docker image. But when I set asterisk `*` to package.json for Puppeteer and use for example tag `14-11.0.0-beta` for docker image `apify/actor-node-puppeteer-chrome` it is installing Puppeteer version 12. So I have to set correct version of Puppeteer on both places.

**Comment by B4nan** [comment]
Might be connected to #71, cc @vladfrangu
