### ISSUE TITLE
Docker image actor-node 18 fails during the build phase

### ISSUE THREAD

**Issue by underfisk** [apify/apify-actor-docker#91]
I'm currently trying to deploy a custom docker image using the recommended docker images but when doing it, it looks like the build base when I do `tsc` or `nest build` (which is what I'm using) will make the build fail

## Dockerfile
```bash
FROM apify/actor-node:18 AS base
#FROM node:18 AS base <-- If i enable this it will work
RUN npm i -g pnpm @nestjs/cli

FROM base AS dependencies

# Create app directory
WORKDIR /app

# Ensure deps are included
COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma/

RUN pnpm i --prod=false

FROM base AS build

WORKDIR /app
COPY . ./
COPY prisma ./prisma
COPY --from=dependencies /app/node_modules ./node_modules

RUN pnpm build
RUN pnpm prune --prod


FROM base AS deploy

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

CMD [ "node", "dist/main.js" ]
```

## Error output

```bash
#13 4.046 assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
#13 4.046 (BuilderBase.h:550 block_for_offset)
#13 4.093  ELIFECYCLE  Command failed.
```

## Additional context
Node version: 18
Platform: Mac M1 (also tried on Azure pipelines with all kinds of Arch, same problem)

**Comment by B4nan** [comment]
Closing as not reproducible, this will be probably about your NPM dependencies. Quick google search points to [this issue](https://github.com/ethereum/solidity/issues/13523#issuecomment-1284130107), where they say it's related to deno and m1, but if things work with the base `node:18` it sounds like you are just missing some system dependency required by one of your NPM packages. 

Our images are meant to be used for actor development, you might need to install more things explicitly if they are needed by your project setup, this doesn't sound like something to address in them.
